[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 10

[preview]
tab_size = 2
image_filter = "catmull-rom"
image_quality = 75

[opener]
edit = [{ run = 'nvim "$@"', block = true }]
